import type { NewInstrument } from "@/lib/db/schema";

export const ETF_SEED: NewInstrument[] = [
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    instrumentType: "etf",
    currentPrice: "450.25",
    allocationRegions: { north_america: 100 },
    allocationSectors: {
      technology: 28, healthcare: 13, financials: 13,
      consumer_discretionary: 12, industrials: 9, communication: 9,
      consumer_staples: 6, energy: 4, utilities: 3, real_estate: 2, materials: 1,
    },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    instrumentType: "etf",
    currentPrice: "385.50",
    allocationRegions: { north_america: 100 },
    allocationSectors: {
      technology: 50, communication: 17, consumer_discretionary: 15,
      healthcare: 8, consumer_staples: 5, industrials: 3, other: 2,
    },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "IWM",
    name: "iShares Russell 2000 ETF",
    instrumentType: "etf",
    currentPrice: "205.75",
    allocationRegions: { north_america: 100 },
    allocationSectors: {
      healthcare: 18, financials: 17, industrials: 16, technology: 14,
      consumer_discretionary: 12, real_estate: 7, energy: 6, materials: 4,
      consumer_staples: 3, utilities: 2, communication: 1,
    },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "VEA",
    name: "Vanguard FTSE Developed Markets ETF",
    instrumentType: "etf",
    currentPrice: "48.30",
    allocationRegions: { europe: 60, asia: 35, oceania: 5 },
    allocationSectors: {
      financials: 18, industrials: 14, healthcare: 12, consumer_discretionary: 11,
      technology: 10, consumer_staples: 9, materials: 8, energy: 6,
      communication: 5, utilities: 4, real_estate: 3,
    },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "VWO",
    name: "Vanguard FTSE Emerging Markets ETF",
    instrumentType: "etf",
    currentPrice: "42.15",
    allocationRegions: { asia: 75, latin_america: 10, africa: 8, europe: 7 },
    allocationSectors: {
      technology: 22, financials: 20, consumer_discretionary: 15,
      communication: 10, energy: 8, materials: 7, industrials: 6,
      consumer_staples: 5, healthcare: 4, utilities: 2, real_estate: 1,
    },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "EFA",
    name: "iShares MSCI EAFE ETF",
    instrumentType: "etf",
    currentPrice: "75.80",
    allocationRegions: { europe: 65, asia: 35 },
    allocationSectors: {
      financials: 17, industrials: 15, healthcare: 13, consumer_discretionary: 12,
      consumer_staples: 10, technology: 9, materials: 8, energy: 5,
      communication: 5, utilities: 3, real_estate: 3,
    },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "AGG",
    name: "iShares Core U.S. Aggregate Bond ETF",
    instrumentType: "bond_fund",
    currentPrice: "98.20",
    allocationRegions: { north_america: 100 },
    allocationSectors: { treasury: 40, corporate: 25, mortgage: 28, government_related: 7 },
    allocationAssetClass: { fixed_income: 100 },
  },
  {
    symbol: "BND",
    name: "Vanguard Total Bond Market ETF",
    instrumentType: "bond_fund",
    currentPrice: "72.50",
    allocationRegions: { north_america: 100 },
    allocationSectors: { treasury: 42, corporate: 24, mortgage: 27, government_related: 7 },
    allocationAssetClass: { fixed_income: 100 },
  },
  {
    symbol: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    instrumentType: "bond_fund",
    currentPrice: "92.30",
    allocationRegions: { north_america: 100 },
    allocationSectors: { treasury: 100 },
    allocationAssetClass: { fixed_income: 100 },
  },
  {
    symbol: "HYG",
    name: "iShares iBoxx High Yield Corporate Bond ETF",
    instrumentType: "bond_fund",
    currentPrice: "76.85",
    allocationRegions: { north_america: 95, international: 5 },
    allocationSectors: { corporate: 100 },
    allocationAssetClass: { fixed_income: 100 },
  },
  {
    symbol: "XLK",
    name: "Technology Select Sector SPDR Fund",
    instrumentType: "etf",
    currentPrice: "175.40",
    allocationRegions: { north_america: 100 },
    allocationSectors: { technology: 100 },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "XLV",
    name: "Health Care Select Sector SPDR Fund",
    instrumentType: "etf",
    currentPrice: "135.60",
    allocationRegions: { north_america: 100 },
    allocationSectors: { healthcare: 100 },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "XLF",
    name: "Financial Select Sector SPDR Fund",
    instrumentType: "etf",
    currentPrice: "38.25",
    allocationRegions: { north_america: 100 },
    allocationSectors: { financials: 100 },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "XLE",
    name: "Energy Select Sector SPDR Fund",
    instrumentType: "etf",
    currentPrice: "85.90",
    allocationRegions: { north_america: 100 },
    allocationSectors: { energy: 100 },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "VNQ",
    name: "Vanguard Real Estate ETF",
    instrumentType: "etf",
    currentPrice: "82.45",
    allocationRegions: { north_america: 100 },
    allocationSectors: { real_estate: 100 },
    allocationAssetClass: { real_estate: 100 },
  },
  {
    symbol: "GLD",
    name: "SPDR Gold Shares",
    instrumentType: "etf",
    currentPrice: "195.70",
    allocationRegions: { global: 100 },
    allocationSectors: { commodities: 100 },
    allocationAssetClass: { commodities: 100 },
  },
  {
    symbol: "SLV",
    name: "iShares Silver Trust",
    instrumentType: "etf",
    currentPrice: "22.40",
    allocationRegions: { global: 100 },
    allocationSectors: { commodities: 100 },
    allocationAssetClass: { commodities: 100 },
  },
  {
    symbol: "AOR",
    name: "iShares Core Growth Allocation ETF",
    instrumentType: "etf",
    currentPrice: "48.90",
    allocationRegions: { north_america: 60, international: 40 },
    allocationSectors: { diversified: 100 },
    allocationAssetClass: { equity: 60, fixed_income: 40 },
  },
  {
    symbol: "AOA",
    name: "iShares Core Aggressive Allocation ETF",
    instrumentType: "etf",
    currentPrice: "65.15",
    allocationRegions: { north_america: 55, international: 45 },
    allocationSectors: { diversified: 100 },
    allocationAssetClass: { equity: 80, fixed_income: 20 },
  },
  {
    symbol: "VUG",
    name: "Vanguard Growth ETF",
    instrumentType: "etf",
    currentPrice: "312.80",
    allocationRegions: { north_america: 100 },
    allocationSectors: {
      technology: 45, consumer_discretionary: 18, healthcare: 12,
      industrials: 10, communication: 8, financials: 4, other: 3,
    },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "VTV",
    name: "Vanguard Value ETF",
    instrumentType: "etf",
    currentPrice: "152.60",
    allocationRegions: { north_america: 100 },
    allocationSectors: {
      financials: 20, healthcare: 18, industrials: 12, consumer_staples: 11,
      energy: 10, utilities: 8, communication: 7, materials: 6,
      technology: 5, other: 3,
    },
    allocationAssetClass: { equity: 100 },
  },
  {
    symbol: "VIG",
    name: "Vanguard Dividend Appreciation ETF",
    instrumentType: "etf",
    currentPrice: "168.90",
    allocationRegions: { north_america: 100 },
    allocationSectors: {
      technology: 22, healthcare: 16, financials: 14, consumer_staples: 13,
      industrials: 12, consumer_discretionary: 10, utilities: 5,
      materials: 4, other: 4,
    },
    allocationAssetClass: { equity: 100 },
  },
];
